Numpy introduction

In [1]:
import numpy as np


In [21]:
npArr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("#2d array",npArr.shape[0], "#1d array", npArr.shape[1], "ALL element", npArr.shape[2])
print(npArr[:, :, 0])
print(npArr.mean(axis=1))

#2d array 2 #1d array 2 ALL element 3
[[ 1  4]
 [ 7 10]]
[[ 2.5  3.5  4.5]
 [ 8.5  9.5 10.5]]


In [29]:
npArr = np.arange(1, 21)

npArr = npArr.reshape((5, 4))

print(npArr[1:3, 1:])
print(npArr[:2, 1:])
print(npArr[1:, 2])

[[ 6  7  8]
 [10 11 12]]
[[2 3 4]
 [6 7 8]]
[ 7 11 15 19]
