Taking Input from User

In [375]:
import numpy as np
import copy as cp
import math
init_state = np.array([
    [3, 1, 2],
    [6, 4, 0],
    [7, 8, 5]
])

goal_state = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

In [362]:
# finding position of 0
pos = np.argwhere(init_state == 0)
pos = pos.tolist()[0]
print(pos)


curr_state = cp.deepcopy(init_state)

# temp = curr_state[pos[0], pos[1]]
# curr_state[pos[0], pos[1]] = curr_state[pos[0], pos[1]+1]
# curr_state[pos[0], pos[1]+1] = pos[]
    # = curr_state[pos[0], pos[1]]

print(curr_state)
print(init_state.shape[0])

[1, 2]
[[3 1 2]
 [6 4 0]
 [7 8 5]]
3


In [363]:
class NodeStates:
    def __init__(self, in_state):
        self.in_state = in_state

    def find_pos(self, val):
        return np.argwhere(self.in_state == val).tolist()[0]

    def swap(self, pos, dir):
        temp = self.in_state[pos[0], pos[1]]
        self.in_state[pos[0], pos[1]] = self.in_state[dir[0], dir[1]]
        self.in_state[dir[0], dir[1]] = temp

    def move_up(self):
        pos = self.find_pos(0)
        if pos[0] == 0:
            return self.in_state
        else:
            dir = [pos[0]-1, pos[1]]
            self.swap(pos, dir)

    def move_down(self):
        pos = self.find_pos(0)
        if pos[0] == self.in_state.shape[0]-1:
            return self.in_state
        else:
            dir = [pos[0]+1, pos[1]]
            self.swap(pos, dir)

    def move_right(self):
        pos = self.find_pos(0)
        if pos[1] == self.in_state.shape[1]-1:
            return self.in_state
        else:
            dir = [pos[0], pos[1]+1]
            self.swap(pos, dir)

    def move_left(self):
        pos = self.find_pos(0)
        if pos[1] == 0:
            return self.in_state
        else:
            dir = [pos[0], pos[1]-1]
            self.swap(pos, dir)

    def manhattan_distance(self, goal_state):
        sum = 0
        for i in range(3):
            for j in range(3):
                c_pos = self.find_pos(goal_state[i][j])
                sum += abs(c_pos[0]-i) + abs(c_pos[1]-j)
                # print(sum)
        return sum

    def misplaced_tiles(self, goal_state):
        sum = 0
        for i in range(3):
            for j in range(3):
                c_pos = self.find_pos(goal_state[i][j])
                if c_pos != [i, j]:
                    sum += 1
        return sum

In [416]:
curr_state = NodeStates(init_state)

# print(curr_state.in_state)
# print(goal_state)
# print(curr_state.misplaced_tiles(goal_state))

steepest ascent hill climbing approach

In [365]:
def get_lowest_cost_successor_md(nodeState, goal_state):
    min_cost = 999999
    lowest_successor = nodeState
    for i in range(4):
        temp_state = nodeState

        if i == 0:
            temp_state.move_up()
            cost = temp_state.manhattan_distance(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)

        if i == 1:
            temp_state.move_down()
            cost = temp_state.manhattan_distance(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)

        if i == 2:
            temp_state.move_left()
            cost = temp_state.manhattan_distance(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)

        if i == 3:
            temp_state.move_right()
            cost = temp_state.manhattan_distance(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)
    return lowest_successor, min_cost


In [366]:
def get_lowest_cost_successor_mt(nodeState, goal_state):
    min_cost = 999999
    lowest_successor = nodeState

    for i in range(4):
        temp_state = nodeState

        if i == 0:
            temp_state.move_up()
            cost = temp_state.misplaced_tiles(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)

        if i == 1:
            temp_state.move_down()
            cost = temp_state.misplaced_tiles(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)

        if i == 2:
            temp_state.move_left()
            cost = temp_state.misplaced_tiles(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)

        if i == 3:
            temp_state.move_right()
            cost = temp_state.misplaced_tiles(goal_state)
            if cost < min_cost:
                min_cost = cost
                lowest_successor = cp.deepcopy(temp_state)
    return lowest_successor, min_cost


Hill climbing with manhattan distance heuristic

In [376]:
def hill_climbing(start_state):
    curr = start_state
    itr = 0

    while True:
        itr+=1
        curr_heuristic = curr.manhattan_distance(goal_state)

        if itr > 300 or curr_heuristic == 0:
            break
        neighbour, heuristic = get_lowest_cost_successor_md(curr, goal_state)
        print(neighbour.in_state, heuristic)

        if heuristic >= curr_heuristic:
            print(curr.in_state)
            print(itr, "iterations")
            return curr
        curr = neighbour
    print(curr.in_state)
    print(itr, "iterations")
    return curr

In [379]:
temp_state = cp.deepcopy(curr_state)
sol = hill_climbing(temp_state)
print("h=",sol.manhattan_distance(goal_state))

[[3 1 0]
 [6 4 2]
 [7 8 5]] 8
[[3 1 2]
 [6 4 0]
 [7 8 5]]
1 iterations
h= 8


Hill climbing with misplaced tiles heuristic

In [380]:
def hill_climbing(start_state):
    curr = start_state
    itr = 0

    while True:
        itr+=1
        curr_heuristic = curr.misplaced_tiles(goal_state)

        if itr > 300 or curr_heuristic == 0:
            break
        neighbour, heuristic = get_lowest_cost_successor_mt(curr, goal_state)
        print(neighbour.in_state, heuristic)

        if heuristic >= curr_heuristic:
            print(curr.in_state)
            print(itr, "iterations")
            return curr
        curr = neighbour
    print(curr.in_state)
    print(itr, "iterations")
    return curr

In [382]:
temp_state = cp.deepcopy(curr_state)
sol = hill_climbing(temp_state)
print("h=", sol.misplaced_tiles(goal_state))

[[3 1 2]
 [6 4 0]
 [7 8 5]] 6
[[3 1 2]
 [6 4 0]
 [7 8 5]]
1 iterations
h= 6


Simulated Annealing Starts From Here

In [258]:
# randomly selected neighbour

import random
import time



def random_select_neighbour_mt(parent_state, goal_state):

    dictn = {}

    for i in range(4):
        temp_state = cp.deepcopy(parent_state)

        if i == 0:
            temp_state.move_up()
            cost = temp_state.misplaced_tiles(goal_state)
            dictn[i] = [temp_state, cost]
            # print(dictn[i][0].in_state)

        if i == 1:
            temp_state.move_down()
            cost = temp_state.misplaced_tiles(goal_state)
            dictn[i] = [temp_state, cost]

        if i == 2:
            temp_state.move_left()
            cost = temp_state.misplaced_tiles(goal_state)
            dictn[i] = [temp_state, cost]

        if i == 3:
            temp_state.move_right()
            cost = temp_state.misplaced_tiles(goal_state)
            dictn[i] = [temp_state, cost]

    lst = []
    lst.append(dictn)
    random.seed(time.time())
    lst = lst[0][random.randrange(0, 4)]
    return lst

In [417]:
# temp_state = cp.deepcopy(curr_state)
# print(temp_state.in_state)
# temp_state = random_select_neighbour_mt(temp_state, goal_state)
#
# print(temp_state[0].in_state)

In [418]:
def simulated_annealing(start_state, T, alpha):
    curr = start_state
    itr = 0

    while True:
        itr += 1
        if T == 0 or itr > 300 or np.array_equal(curr.in_state, goal_state):
            print(curr.in_state)
            print(itr, "iterations")
            return curr

        next_ = random_select_neighbour_mt(curr, goal_state)
        curr_val = curr.misplaced_tiles(goal_state)

        delE = next_[1] - curr_val
        # print(itr)
        if delE >= 0:
            curr = next_[0]
        elif random.random() < math.exp(delE/T):
            curr = next_[0]
        T = alpha * T
        # print(T)
    print(curr.in_state)
    print(itr, "iterations")
    return curr


In [388]:
temp_state = cp.deepcopy(curr_state)
sol = simulated_annealing(temp_state, 20, 0.97)
print("h=", sol.misplaced_tiles(goal_state))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
22 iterations
h= 0


In [323]:
def random_select_neighbour_md(parent_state, goal_state):

    dictn = {}

    for i in range(4):
        temp_state = cp.deepcopy(parent_state)

        if i == 0:
            temp_state.move_up()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]
            # print(dictn[i][0].in_state)

        if i == 1:
            temp_state.move_down()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]

        if i == 2:
            temp_state.move_left()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]

        if i == 3:
            temp_state.move_right()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]

    lst = []
    lst.append(dictn)
    random.seed(time.time())
    lst = lst[0][random.randrange(0, 4)]
    return lst

In [403]:
def random_restart(start_state):
    dictn = {}

    for i in range(4):
        temp_state = cp.deepcopy(start_state)

        if i == 0:
            temp_state.move_up()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]
            # print(dictn[i][0].in_state)

        if i == 1:
            temp_state.move_down()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]

        if i == 2:
            temp_state.move_left()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]

        if i == 3:
            temp_state.move_right()
            cost = temp_state.manhattan_distance(goal_state)
            dictn[i] = [temp_state, cost]

    lst = []
    lst.append(dictn)
    random.seed(time.time())
    lst = lst[0][random.randrange(0, 4)]
    return lst[0]

In [408]:
def simulated_annealing(start_state, T, alpha):
    curr = start_state
    itr = 0

    while True:
        itr += 1
        if np.array_equal(curr.in_state, goal_state) or T == 0 or itr > 300:
            print(curr.in_state)
            print(itr, "iterations")
            return curr
        # elif T == 0 or itr > 300:
        #     curr = random_restart(start_state)

        next_ = random_select_neighbour_mt(curr, goal_state)
        curr_val = curr.misplaced_tiles(goal_state)

        delE = next_[1] - curr_val
        # print(itr)
        if delE >= 0:
            curr = next_[0]
        elif random.random() < math.exp(delE/T):
            curr = next_[0]
        T = alpha * T
        # print(T)
    print(curr.in_state)
    print(itr, "iterations")
    return curr

In [415]:
temp_state = cp.deepcopy(curr_state)
sol = simulated_annealing(temp_state, 20, 0.97)
print("h=", sol.manhattan_distance(goal_state))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
37 iterations
h= 0
